// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD32jAtN_HUW2wZMuHnoLsO5kEHWSkdhqk',
    appId: '1:1003358302870:android:957f83429c4a7a1d8e08b7',
    messagingSenderId: '1003358302870',
    projectId: 'employee-management-9450e',
    databaseURL: 'https://employee-management-9450e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-management-9450e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt4rWK3GrOy546Mg_XT4n8w6Kr7OPZNk0',
    appId: '1:1003358302870:ios:770f787f842e7b478e08b7',
    messagingSenderId: '1003358302870',
    projectId: 'employee-management-9450e',
    databaseURL: 'https://employee-management-9450e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-management-9450e.appspot.com',
    iosBundleId: 'com.example.CompanyDatabase',
  );
}
